# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-12 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog_posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('tag', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=120)),
            ],
        ),
    ]
