# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-12 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_posts',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
